### ISSUE TITLE
Automate Image Sprites

### ISSUE THREAD

**Issue by elseloop** [connectivedx/Phoenix#90]
One of the greatest strengths of Compass is its ability to create image sprites on the fly. This proves really handy not only in saving time, but also in instances where you have a series of elements with background images that you can loop through and assign with some common naming conventions. It can also get really, really slow.

I'd like to investigate bringing in some non-Ruby solution to this as part of Phoenix's Gulp build. [CSS Sprites](https://github.com/aslansky/css-sprite) looks promising (though I haven't tested it at all). It appears to work exactly like the Compass process: pass it a folder of images, it makes a sprite from them, and it makes the original image file name available as a Sass variable for easily accessing `background-position` and size values.

I'd be really interested in hearing any other options people have found as well. Or arguments against doing something like this.

**Comment by ajmueller** [comment]
@devinrayolsen since you said you'd like to research this, please post any findings here for discussion.

**Comment by devinrayolsen** [comment]
A project I'm working on right now uses grunt Spritesmith; it's pretty amazing and easy to use. There are two gulp versions (the one linked above is the correct working one), both inherit the same custom options that come with the standard npm Spritesmith module.

I went ahead and setup a new feature/spritesmith branch this afternoon, so give it a try.
Just drop your loose image files in src/img/css/sprite-files and the sprite driver will generate both your sprite (src/img/css/compiled-sprite.png) and sprite's SCSS variables / mixins (src/css/variables/_sprites.scss).

When you want to use an image from the compiled-sprite.png, simply use:
@include sprite($image-file-name);

This means we no longer have to craft our sprites by hand any longer, nor do we ever have to maintain image positions any-more. There are a handful of algorithms settings for the image/varable generation we can play with if we want; I picked one I liked from the Bruderhof project (alt-diagonal).

The new sprite driver should be running prior to img.js driver so any additional image tasks built out in img.js should naturally be applied to the generated sprite as well. That said, there IS a img min / quality setting I didn't include in the sprite driver that we might want to talk about.

The one down side I don't like right now and can't find info on is how to generate the handful of mixins for the sprites out of src/css/variables/_sprites.scss into src/css/mixins/_sprites.scss and keep the variables and mixins clean and seperate, but nothing so far.

**Comment by kamsar** [comment]
Would there ever be a use case for a project to need more than one compiled
sprite image?

**Comment by devinrayolsen** [comment]
Should really try to promote the idea of one sprite to rule them all for many reasons. That said, I could see the need for wanting to make more than one sprite for multi site purposes etc.

We can support this but have a few decisions to make:

One option is we can make all images with in the root of  src/css/img/sprite-files/*.* always compile out to compiled-sprite.png (or maybe main-sprite.png would be a better name). Then any sub-directories and their containing images within /sprite-files/**/* would represent additional sprites. All sprite variables should always end up in the same spot as now and not split up for organization reasons.

The other option is to extend out new configure options to the gulp config for the sprite driver. New options to allow developers to configure each individual desired sprite's source location, compiled image location / name, the algorithm type.

In either above scenario, we would need to loop over the source path(s) (current set in gulp config of the sprite driver) in our sprite driver's build pipeline function. I'm not seeing any way to gather paths here yet.. but I think that would be step one.

Thoughts?

**Comment by kamsar** [comment]
I like that subdirectory idea. For example:

`src/img/css/sprite-files/monkey/foo.png`

would transfer into:

`dist/img/css/sprites/monkey.png`

(or something similar)

That'd allow for creating arbitrary numbers of sprites AND naming the output file via the parent folder. Thoughts?

**Comment by ajmueller** [comment]
Thanks for putting this together @devinrayolsen!  Just a couple notes:

- Can you change the variables to be camel cased to match other variables?
- Should [this line](https://github.com/connectivedx/Phoenix/blob/feature/spritesmith/Assets/src/css/variables/_sprites.scss#L24) use the previously defined variables for x, y, offset-x, offset-y, etc.?
- The variables might be good candidates for a map, perhaps along the lines of:

    ```scss
    $githubDownloadTarGrey: (
        name: 'githubDownloadTarGrey',
        x: 255px
        ...
    );
    ```

- With the update to Sassdocs for our documentation system, the images you used here to create the sprite are going away.  I'm not sure if we have other images that would be good for spriting (as seen in the [feature/documentation branch](https://github.com/connectivedx/Phoenix/tree/feature/documentation/Assets/src/img/css) we have very few images left).  Any ideas here about something we could add to show as a baseline example for spriting?  Or maybe this could simply be a documented feature that doesn't have an applied example out of the box?

**Comment by devinrayolsen** [comment]
There is an opportunity to hook into the variable names and format them in the sprite driver, however the variables are reflective of the actual loose file names. If the desire for camel case vars is needed, simply changing the loose file's name to camel case. I don't think its wise to have the variable pattern not match loose file name's pattern; will cause lots of typos or double checking at the very least and annoying to track down if we drop images from the sprites at a later point.

That variable mixup is not 100% understood by me yet, but I think you are correct. I want to try some other algorithm types and spacing options and see if I can trim down the vars a bit.

I've got nothing in mind for actual release other than what I put up for quick demo purposes, I'd be ok leaving it empty. No need to add to the file size to simply demonstrate something if its not really needed.

**Comment by devinrayolsen** [comment]
@kamsar, I've started the process for the sub folder sprite buildout. There is no native way to combine the piped css processes into the same file with out a little fs support, but still do able.

@ajmueller, I just pushed a few changes to include a new /build/lib/sprite.handlebars template file that gives us control to both clean up the variables/_sprite.scss file, but also setup mapping. Should be much better and the mixin updated.

More changes shortly.

**Comment by ajmueller** [comment]
@devinrayolsen, @elseloop and I were just working on a client project and were thinking that social icons would make for a good demo in Phoenix.  They're used in almost every project and would be relatively quick to put together an example.  We'd definitely want an @2x version as well for high-resolution displays.  Thoughts?

**Comment by ajmueller** [comment]
@devinrayolsen here's a good sprite example from a client that has social icons:  http://fed.isitedesign.net/content/ohsu-psr-build/_resources/img/css/sprite@2x.png

**Comment by devinrayolsen** [comment]
Great idea guys.

Ok from the top, gulp.spritesmith has retina support but requires every image we sprite now to be accompanied with a retina version or build wont complete with warning about sprite mismatch. Not really a problem as discussed yesterday @ajmueller, but wanted to put a reminder up.

That said, the guy who wrote gulp.spritesmith then decided to ignore his own rule by producing mass amounts variables, list and helper vars to allow you to use @include sprite() and @include retina_sprite() as two separate mixins... :-1: So after a ton of backwards reading of his mixins, I consolidated all his work down to just one mixin again that has retina support so we can continue to use just @include sprite().

The big snag I ran into was the @ symbol in file names. Because we have the retina images files being named with an @ symbol, and spritesmith produces variables from these file names, we run into errors at build with them. The mappings just break cause the characters can't be escaped due to the sheet considering them an entry point to a media query (I assume). So because of this I've gone back to the sprite driver and changed the retina filter from *@2x* to just *2x* and changed the image files names from @2x.png to -2x.png

I have not included the social icons yet, doing that this afternoon.

**Comment by elseloop** [comment]
I have literally nothing of value to add here, I just wanted to say I’m *really* excited about having this resource and reading how close you are, @devinrayolsen, I'm like 

![](http://i.giphy.com/Gc0rAVLjgdPfq.gif)

Like I said, nothing of value. Just a drive-by :+1:

**Comment by stoff** [comment]
Seriously.  he's sitting behind me and doing that.  MAKE IT STOP.

**Comment by devinrayolsen** [comment]
@kamsar multi-sprite building is completed or least up.
Having said that, some stuff had to change about the setup of multi-sprite, we could not do the auto-magic method for path conflicts if a person also configures the same path with in the gulpfile.js driver path. Thus, instead of trying wrangle with this, figured it was trying to tell me something and left the ability to define more sprites within the gulpfile.js sprite driver's paths glob.

Going to spend some more time this weekend seeing if I can break it or trim up some areas.

**Comment by ajmueller** [comment]
I'm just now catching up.  This is awesome, Devin, thanks.  I'm looking forward to testing it out (it looks like Dan has already integrated it on a client project he and I are working on).

**Comment by ajmueller** [comment]
As I'm finally getting some final time to work on Phoenix, I should provide an update here (and I'm guessing @elseloop can provide more information than I can).  We tried Spritesmith on KinderCare with fairly poor results.  @elseloop, please correct me if anything I say is incorrect.

The initial build would give us errors since some of the variables used by and created by the plugin did not yet exist.  Naturally this would fix itself once our builds restarted, but it was a strange experience and a bit clunky.  In addition, I believe there were some issues with sizing and positioning.  I don't know the details since @elseloop did the work, but needless to say we did not end up using Spritesmith on KinderCare in the end.  It was faster for us to create the sprite on our own.  Considering most of our new projects these days tend to have minimal spriting needs, I'm curious if having this plugin will provide enough value and efficiency to warrant its use.

**Comment by devinrayolsen** [comment]
Agree, I stopped working on this in pursuit of the SVG sprite plugin.
More information around this instead as we move over to SVG everything.

**Comment by stoff** [comment]
@elseloop; @devinrayolsen: I think @devinrayolsen's instinct to close this was correct; is there another issue for the SVG sprite?  seems like that task can/should be handled separately and linked here.

**Comment by elseloop** [comment]
Yeah, I missed that he'd closed and reopened this. Let's close it. I'll open the new SVG sprite issue now.
